export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_DETAILES_REQUEST = 'PRODUCT_DETAILES_REQUEST';
export const PRODUCT_DETAILES_SUCCESS = 'PRODUCT_DETAILES_SUCCESS';
export const PRODUCT_DETAILES_FAIL = 'PRODUCT_DETAILES_FAIL';


